// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.5
// source: shipment.protoc

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Item request for shipment creation
type ShipmentItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentItemRequest) Reset() {
	*x = ShipmentItemRequest{}
	mi := &file_shipment_protoc_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentItemRequest) ProtoMessage() {}

func (x *ShipmentItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_protoc_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentItemRequest.ProtoReflect.Descriptor instead.
func (*ShipmentItemRequest) Descriptor() ([]byte, []int) {
	return file_shipment_protoc_rawDescGZIP(), []int{0}
}

func (x *ShipmentItemRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ShipmentItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Request message for creating a shipment
type CreateShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*ShipmentItemRequest `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_shipment_protoc_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_protoc_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_shipment_protoc_rawDescGZIP(), []int{1}
}

func (x *CreateShipmentRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateShipmentRequest) GetItems() []*ShipmentItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

// Response message for creating a shipment
type CreateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ShipmentData          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_shipment_protoc_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_protoc_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_shipment_protoc_rawDescGZIP(), []int{2}
}

func (x *CreateShipmentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateShipmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateShipmentResponse) GetData() *ShipmentData {
	if x != nil {
		return x.Data
	}
	return nil
}

// Shipment data in response
type ShipmentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    int64                  `protobuf:"varint,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Items         []*ShipmentItem        `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentData) Reset() {
	*x = ShipmentData{}
	mi := &file_shipment_protoc_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentData) ProtoMessage() {}

func (x *ShipmentData) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_protoc_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentData.ProtoReflect.Descriptor instead.
func (*ShipmentData) Descriptor() ([]byte, []int) {
	return file_shipment_protoc_rawDescGZIP(), []int{3}
}

func (x *ShipmentData) GetShipmentId() int64 {
	if x != nil {
		return x.ShipmentId
	}
	return 0
}

func (x *ShipmentData) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ShipmentData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShipmentData) GetItems() []*ShipmentItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShipmentData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Shipment item in response
type ShipmentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentItem) Reset() {
	*x = ShipmentItem{}
	mi := &file_shipment_protoc_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentItem) ProtoMessage() {}

func (x *ShipmentItem) ProtoReflect() protoreflect.Message {
	mi := &file_shipment_protoc_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentItem.ProtoReflect.Descriptor instead.
func (*ShipmentItem) Descriptor() ([]byte, []int) {
	return file_shipment_protoc_rawDescGZIP(), []int{4}
}

func (x *ShipmentItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ShipmentItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_shipment_protoc protoreflect.FileDescriptor

const file_shipment_protoc_rawDesc = "" +
	"\n" +
	"\x0fshipment.protoc\x12\bshipment\"C\n" +
	"\x13ShipmentItemRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"g\n" +
	"\x15CreateShipmentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x123\n" +
	"\x05items\x18\x02 \x03(\v2\x1d.shipment.ShipmentItemRequestR\x05items\"r\n" +
	"\x16CreateShipmentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x04data\x18\x03 \x01(\v2\x16.shipment.ShipmentDataR\x04data\"\xaf\x01\n" +
	"\fShipmentData\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\x03R\n" +
	"shipmentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12,\n" +
	"\x05items\x18\x04 \x03(\v2\x16.shipment.ShipmentItemR\x05items\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"<\n" +
	"\fShipmentItem\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity2h\n" +
	"\x0fShipmentService\x12U\n" +
	"\x0eCreateShipment\x12\x1f.shipment.CreateShipmentRequest\x1a .shipment.CreateShipmentResponse\"\x00B'Z%billing-system/shipment_service/protob\x06proto3"

var (
	file_shipment_protoc_rawDescOnce sync.Once
	file_shipment_protoc_rawDescData []byte
)

func file_shipment_protoc_rawDescGZIP() []byte {
	file_shipment_protoc_rawDescOnce.Do(func() {
		file_shipment_protoc_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipment_protoc_rawDesc), len(file_shipment_protoc_rawDesc)))
	})
	return file_shipment_protoc_rawDescData
}

var file_shipment_protoc_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shipment_protoc_goTypes = []any{
	(*ShipmentItemRequest)(nil),    // 0: shipment.ShipmentItemRequest
	(*CreateShipmentRequest)(nil),  // 1: shipment.CreateShipmentRequest
	(*CreateShipmentResponse)(nil), // 2: shipment.CreateShipmentResponse
	(*ShipmentData)(nil),           // 3: shipment.ShipmentData
	(*ShipmentItem)(nil),           // 4: shipment.ShipmentItem
}
var file_shipment_protoc_depIdxs = []int32{
	0, // 0: shipment.CreateShipmentRequest.items:type_name -> shipment.ShipmentItemRequest
	3, // 1: shipment.CreateShipmentResponse.data:type_name -> shipment.ShipmentData
	4, // 2: shipment.ShipmentData.items:type_name -> shipment.ShipmentItem
	1, // 3: shipment.ShipmentService.CreateShipment:input_type -> shipment.CreateShipmentRequest
	2, // 4: shipment.ShipmentService.CreateShipment:output_type -> shipment.CreateShipmentResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_shipment_protoc_init() }
func file_shipment_protoc_init() {
	if File_shipment_protoc != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipment_protoc_rawDesc), len(file_shipment_protoc_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipment_protoc_goTypes,
		DependencyIndexes: file_shipment_protoc_depIdxs,
		MessageInfos:      file_shipment_protoc_msgTypes,
	}.Build()
	File_shipment_protoc = out.File
	file_shipment_protoc_goTypes = nil
	file_shipment_protoc_depIdxs = nil
}
